# -*- coding: utf-8 -*-
"""Mediana  e moda de uma variável.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AJeuDdjQnfgbgnGimBAHMpE9nUa9HaOy

# Mediana
"""

import pandas as pd

df = pd.DataFrame (data ={'Matheus':[6,7,9,10,7,4,5],
                          'João':[5,8,9,2,10,6,8],
                          'Fabi':[9,6,10,7,8,4,6]},
index = ['Estatística',
         'Macroeconomia',
         'Contabilidade',
         'Ciencias Sociais',
         'Econometria',
         'Sistemas',
         'Microeconomia'])
df.rename_axis('Matérias',axis = 'columns',inplace = True)
df

notas_matheus = df.Matheus
notas_matheus

notas_matheus = notas_matheus.sort_values()

notas_matheus

# resetando index para ver a posição
notas_matheus = notas_matheus.reset_index()
notas_matheus

#numero impar de elementos
n = notas_matheus.shape[0]
elemento_md = (n+1)/2
elemento_md

notas_matheus.loc[elemento_md -1]

"""## Usando Pandas"""

notas_matheus.median()



"""#Moda"""

df

df.mode()

"""## multimodal"""

exemplo = pd.Series([1, 2, 2, 3, 4, 4, 5, 6, 6])
exemplo.mode()

